//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.WorkplaceManagementSystem.GetDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDataService.IGetDataService")]
    public interface IGetDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetMachineData", ReplyAction="http://tempuri.org/IGetDataService/GetMachineDataResponse")]
        CCS.WorkplaceManagementSystem.Models.Machine GetMachineData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetMachineData", ReplyAction="http://tempuri.org/IGetDataService/GetMachineDataResponse")]
        System.Threading.Tasks.Task<CCS.WorkplaceManagementSystem.Models.Machine> GetMachineDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetDeskData", ReplyAction="http://tempuri.org/IGetDataService/GetDeskDataResponse")]
        CCS.WorkplaceManagementSystem.Models.Section[] GetDeskData(int status1, int status2, int status3, int status4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetDeskData", ReplyAction="http://tempuri.org/IGetDataService/GetDeskDataResponse")]
        System.Threading.Tasks.Task<CCS.WorkplaceManagementSystem.Models.Section[]> GetDeskDataAsync(int status1, int status2, int status3, int status4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataServiceChannel : CCS.WorkplaceManagementSystem.GetDataService.IGetDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataServiceClient : System.ServiceModel.ClientBase<CCS.WorkplaceManagementSystem.GetDataService.IGetDataService>, CCS.WorkplaceManagementSystem.GetDataService.IGetDataService {
        
        public GetDataServiceClient() {
        }
        
        public GetDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CCS.WorkplaceManagementSystem.Models.Machine GetMachineData(int value) {
            return base.Channel.GetMachineData(value);
        }
        
        public System.Threading.Tasks.Task<CCS.WorkplaceManagementSystem.Models.Machine> GetMachineDataAsync(int value) {
            return base.Channel.GetMachineDataAsync(value);
        }
        
        public CCS.WorkplaceManagementSystem.Models.Section[] GetDeskData(int status1, int status2, int status3, int status4) {
            return base.Channel.GetDeskData(status1, status2, status3, status4);
        }
        
        public System.Threading.Tasks.Task<CCS.WorkplaceManagementSystem.Models.Section[]> GetDeskDataAsync(int status1, int status2, int status3, int status4) {
            return base.Channel.GetDeskDataAsync(status1, status2, status3, status4);
        }
    }
}
